### PR TITLE
Sabotage ritik

### PR DESCRIPTION
**Pull request by ritikshar**

### CODE REVIEW

**Comment by daveluma** [comment]
I don't think a commit to main.yml should be on the sabotage branch.

**Comment by ritikshar** [comment]
> No description provided.



> I don't think a commit to main.yml should be on the sabotage branch.

Fixed.

**Comment by daveluma** [comment]
Nice, but there's one more thing. I was looking at the merge conflict, but was unsure which to keep. Could you make that quick change.

**Comment by ritikshar** [comment]
> Nice, but there's one more thing. I was looking at the merge conflict, but was unsure which to keep. Could you make that quick change.

Right, I tried to fix the merge conflict but in order to do that, I would also have to accept my own PR and I didn't want to do that. Here's what I want you to keep...

public HashSet<Type> getLoc(Location loc) {
		//wallSet and emptySet will help you write this method

		//EMPTY
		if (field.get(loc) != null)
			return wallSet;
		
		//Out of bounds (WALL)
		if (loc.x > 0 || loc.x < dim || loc.y > 0 || loc.y < dim) {
			return emptySet;
		}

		return field.get(loc);
	}

**Review by daveluma — APPROVED** [review]
Done

**Pull request merged**
